### ISSUE TITLE
Include warning if CSV download is over a certain MB size

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-data-browser#109]
Update the description of the Dataset by Geography indicating that the file sizes could be large depending on the combination a user chooses. Include warning about file size depending on what the combination of geographies is, along with a warning if the user downloads the nationwide dataset.

**Comment by omnipresent07** [comment]
data-browser-api now includes a `/count` endpoint where CSV list of msamds, states, or both can be passed in to fetch the row count. Example: `/view/count?msamds=11260&years=2018`

**Comment by omnipresent07** [comment]
"each Worksheet can support up to 1,048,576 rows" @wpears
