### ISSUE TITLE
Data Browser content writing 

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-data-browser#11]
Write the intro and explanatory content for the hmda-data-browser pages. 

- Data browser homepage
- Subsets of data page (Variable selection page & aggregation/download page)
- Download by Geography page

**Comment by chynnakeys** [comment]
Here is the data browser text: https://docs.google.com/document/d/1T6f4z0jJzU65yxAnZrmfpKzS4YPdoMJVYguKK3B1_Q4/edit
