### ISSUE TITLE
beta banner navigation links are not functional

### ISSUE THREAD

**Issue by zencircle** [cfpb/hmda-data-browser#128]
Clicking "home" or "Databrowser" button does not change anything since they both point to the same page
![image](https://user-images.githubusercontent.com/25303681/62157621-980bc180-b2db-11e9-874e-da95fb4c04f0.png)

On page2 there is "additional" button to return to home page 
![image](https://user-images.githubusercontent.com/25303681/62157685-bd003480-b2db-11e9-96d1-4991241b8b0a.png)

**Comment by wpears** [comment]
This is working as intended
