### ISSUE TITLE
Multiple steps to download filtered data

### ISSUE THREAD

**Issue by MattPerrine** [cfpb/hmda-data-browser#159]
Some users were confused by the 'two-step' download process (e.g., once they select a geography and apply filters they need to view the data summary before they can download the filtered data)

**Comment by meissadia** [comment]
With the latest user flow that adjusts the 'Download Dataset' button to always download the most-filtered data available, based on Geography/Institution/Variable selections, it seems this issue has been addressed.

**Comment by ericspry** [comment]
@MattPerrine  please close if no longer needed.
