### ISSUE TITLE
Add FAQ link to Data browser home page

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-data-browser#161]
After the intro sentence on the homepage, add a comment about FAQs
"For questions about the HMDA Data Browser, visit out FAQ page" (the FAQ page should link to https://hmda4.demo.cfpb.gov/documentation/2018/faq/)

**Comment by chynnakeys** [comment]
@wpears our is spelled wrong. Sorry! 

Can we also remove the period after FAQ 

For questions about the HMDA Data Browser, visit our FAQ page.

**Comment by wpears** [comment]
Closed by 2625d821fc612a3cc9e33e36c6d6806c384686cc There actually isn't a period after FAQ, it's just part of the underline :)
