### ISSUE TITLE
CSV files not downloading in Firefox

### ISSUE THREAD

**Issue by MattPerrine** [cfpb/hmda-data-browser#162]
Unable to download csv files in Firefox (versions below). Actions taken:

Select Geography - Pennsylvania
Add filter - Action Taken Denied
Summary Table displays ok
Clicked the 'Download Filtered Data' button and nothing happened. 

Same issue occurred when selecting a geography and then 'Download Dataset' button.

Firefox 68.0.2 (Mac)
Firefox 69 (Mac)

**Comment by omnipresent07** [comment]
This seems to be an issue in Windows as well
