### ISSUE TITLE
Identify data to feature in maps & graphs section

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-data-browser#19]

**Comment by Kibrael** [comment]
MSA level data comparison

**Comment by Kibrael** [comment]
@Kibrael will meet with Office of Research to discuss graphs that can support the upcoming Data Point article.

**Comment by Kibrael** [comment]
Below are initial prototype graphs based on the [HMDA Data Point 2017 article](https://files.consumerfinance.gov/f/documents/bcfp_hmda_2017-mortgage-market-activity-trends_report.pdf). These graphs are taken from Figure 2 and Table 1A. 

In stakeholder discussions it was recommended that we include a geography level filter. This filter would allow parties to drill down into the differences between the national aggregations (discussed in the Data Point) and geographies of interest (most commonly an MSA). 

**There is a tradeoff decision that needs to be made:**
Do we want to add UI filtering capability or do we want to have many charts? I am in favor of having UI level filtering and fewer charts. This will make the taxonomy of the data visualization webpage easier to manage while making each chart/graphic much more powerful. The downside is that each will take more work to produce.

**Adding filtering opens up the following:**
- Titles need to match filters selected
- Should users be allowed to select multiple filters where such is appropriate (such as demographics)?

If we choose to add filters to graphics, this can be done iteratively starting with geography and then working through them based on feedback or ease of addition.


**Other nice to have features:**
- Toggles that allow the user to switch between counts and loan amount aggregations

- Toggles that allow user to switch between percent and the aggregation
- Download the aggregate data for this visualization button that allows a user to get a CSV or Pipe delimited version of the aggregate data used to power the visualization. JSON is cool, but I think less useful to the targeted user base.
-Download raw LAR data behind the aggregation button that allows a user to get the unique URL for the query that would result in the same aggregation that powered the visualization. This would be for public data only (disable when the visualization uses non public fields or granularity).

Adding the same or similar filters to a visualization set may produce the same or similar aggregations of data. It is important to remember that recombining data into different visualizations tells a different story. The proposal for figure 2 is very similar to what could be created with table 1A data given a certain filter subset. However, I think the purpose of the visualization is different enough to warrant that both be considered.

[initial Data Browser graphics workbook.xlsx](https://github.com/cfpb/hmda-data-browser/files/3303470/initial.Data.Browser.graphics.workbook.xlsx)
