### ISSUE TITLE
Build out "Subsets of Data" UI 

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-data-browser#2]
Based on the mockups provide by @mattperrine, we want to further build out the UI for the "subsets of data" functionality in the data browser to begin getting feedback from stakeholders.

Initial subsets of data screen:

1) Add capability to select MSA, once State has been selected (selecting MSA is optional)
-For the actual functionality, we should make it clear that selecting a state is also optional (users are not required to filter by geography).  Could be a checkbox for "Nationwide" which then greys out the select state/MSA (just ideas)

2) Add the Variable 1 and Variable 2 drop down boxes. 

3) Add Back & Next buttons 

For the next part, we can use a single scenario of selecting 2 defined filters in order to show the potential functionality for user feedback. 

1) For Variable 1, include "Action Taken" in the drop down. 
- Select Action Taken from the drop down
- Show the secondary box that has checkboxes to select the relevant Action Taken(s) that the user wants to select. The checkboxes should be 1 - Loan Originated, 2 - Approved but not accepted, 3 - Denied, 4 - Withdrawn, 5 - Closed for Incompleteness, 6 - Purchased Loan, 7 - Preapproval denied, 8 - Preapproval approved but not accepted 
- In this scenario, select checkboxes for just 1 - Originated and 6 - Purchased 

2) For Variable 2, include "Race" in the drop down 
- Select "Race" from the drop dpwn
- Show the secondary box that has checkboxes to select the relevant Race(s) that the user wants to select. The checkboxes should be American Indian or Alaska Native, Asian, Black or African American, Native Hawaiian or Pacific Islander, White, 2 or more minority races, Joint and Not Available. 
- In this scenario, select Asian and White 

3) Select Next

WIP - I'll update this with instructions for the UI after "Next" is selected.

**Comment by keileyo** [comment]
Coming back to this...

After selecting the "Next" button in the scenario above, there next screen should:

1) Show a basic table of aggregations of number of records /  total dollar amount by the selected variables. 

![image](https://user-images.githubusercontent.com/13036571/56816404-02bbe580-6833-11e9-85ad-c893ba497a0c.png)


2) Opportunity to download the selected dataset in a .csv format

**Comment by MattPerrine** [comment]
<img width="380" alt="image" src="https://user-images.githubusercontent.com/25694077/56959536-b666f300-6b1b-11e9-861a-b7097b9108c8.png">

<img width="380" alt="image" src="https://user-images.githubusercontent.com/25694077/56959556-c4b50f00-6b1b-11e9-9144-10a64632d7af.png">

<img width="380" alt="image" src="https://user-images.githubusercontent.com/25694077/56959570-d4ccee80-6b1b-11e9-9d4b-c4494b643854.png">
