### ISSUE TITLE
Separate selection of Institution 

### ISSUE THREAD

**Issue by meissadia** [cfpb/hmda-data-browser#203]
Based on Matt's mockup, create a separate drop down for Institution selection

**Comment by wpears** [comment]
In this model, can institutions and geographies be mixed? Does/will that backend support that?

**Comment by meissadia** [comment]
My understanding from Matt's demo was that only when Nationwide was selected would the user be able to specify LEIs, which boils down to an Institution search at the API level.

From some quick tests via Postman it looks like passing LEIs along with Geographies is supported by both the aggregations and CSV endpoints,.
