### ISSUE TITLE
Subsets of Data Variables

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-data-browser#3]
Based on user interviews, the following subset of HMDA data variables are where we should start with the 
-  action taken,
- loan type
- loan purpose, 
- race,
- ethnicity, 
- sex, 
- lien status 
- construction method
-  total units
- dwelling type is (derived from product segmentation)
- loan product (derived field from product segmentation)

Others that are harder to implement
- income 
- denial reasons

Aggregations should be by 
- loan amount
- number of records

**Comment by keileyo** [comment]
Just to be clear on the initial data browser requirement and the select variables listed above:

The "two filter" variable capability means that the drop downs for Variable 1 & Variable 2 should contain the 11 variables listed above and the aggregation tables / csv outputs should be any combination of the two variables selected above (Action Taken & Race is just the example we are using to start getting user feedback).

**Comment by chynnakeys** [comment]
As we discussed, the number code that corresponds with some of the descriptions should be included in the UI. 
Loan type should be displayed with the values:
1 - Conventional (not insured or guaranteed by FHA, VA, RHS, or FSA)
2 - Federal Housing Administration insured (FHA)
3 - Veterans Affairs guaranteed (VA)
4 - USDA Rural Housing Service or Farm Service Agency guaranteed (RHS or FSA)

Loan Purpose:
1 - Home purchase
2 - Home improvement
31 - Refinancing
32 - Cash-out refinancing
4 - Other purpose
5 - Not applicable

Lien Status:
1 - Secured by a first lien
2 - Secured by a subordinate lien

Construction Method:
1 - Site-built
2 - Manufactured Home
