### ISSUE TITLE
Variable Checkbox UI bug in Safari 12 

### ISSUE THREAD

**Issue by BarakStout** [cfpb/hmda-data-browser#32]
When trying to click variable checkboxes on subsets of data, the containers reload and don't update the view. This only happens in Safari. Works normally in other browsers. See video. 

![out](https://user-images.githubusercontent.com/34528865/59110006-24b58700-890c-11e9-9cc7-11ef0bac0c69.gif)

**Comment by wpears** [comment]
Closed in https://github.com/cfpb/hmda-data-browser/commit/515a088b093cd4dece58a541fb256d1553a95f69
