### ISSUE TITLE
Entire Dataset download is not in csv format

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-data-browser#38]
Currently unable to open the csv download after downloading the entire dataset from this page: https://hmda4.demo.cfpb.gov/data-browser/all-data/2018

This is how the download displays: 
![image](https://user-images.githubusercontent.com/41752348/59511724-8b0b4e00-8ea6-11e9-97a7-20c6d90e5b4d.png)

For comparison, this is how the download displays on the subsets of data page: 
![image](https://user-images.githubusercontent.com/41752348/59511789-b68e3880-8ea6-11e9-81bf-97a8ee71ef1b.png)

**Comment by wpears** [comment]
Fixed in https://github.com/cfpb/hmda-data-browser/commit/23c1ed1f9fa8b6c9c3959149a93b2c681b3d84a8
