### ISSUE TITLE
Remove bullets from home page of data browser

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-data-browser#7]
- Remove bullets from the descriptions on the home page of the data browser

- Change name in dropdown box to Variable 1 & Variable 2
![image](https://user-images.githubusercontent.com/41752348/57393501-3848c300-7191-11e9-9b64-431bbb4585e8.png)

**Comment by PatrickHSI** [comment]
@chynnakeys  we should be able to close this issue , bullets were removed from the data-browser home page and we're no longer using this format for the variables. 

https://hmda4.demo.cfpb.gov/data-browser/
