### ISSUE TITLE
Add clearer language to dataset page to better describe what a user can do for each option

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-data-browser#76]
- Change “Geography of HMDA data” title to “HMDA Dataset Filtering”
- Add description underneath HMDA Dataset Filtering: “Download CSVs of HMDA data. These files contain all data fields available in the public data record (with hyperlink to list of fields available - to be updated with link) and can be used for advanced analysis.”

- Add subtitle about geography dropdown entitled “Dataset by Geography” 
- Add description below dropdown “Filter HMDA data by geography levels: nationwide, state, & MSA/MD.” In the dropdown, include instructions "Select or type a geography level"

- Add subtitle: “Dataset by Pre-selected Filters” and description: “Narrow down your geography selection by filtering popular variables”

![image](https://user-images.githubusercontent.com/41752348/60623109-e185f100-9daf-11e9-8cff-3a425c1f5839.png)

**Comment by wpears** [comment]
I'm somewhat concerned about the term "geography level" in the placeholder. Although it's defined in the subheader, for a call to action, I don't think we should introduce an arbitrary term. Also, I think the language of the placeholder itself is a bit troublesome, as it almost seems to imply they should type the name of a level itself, ie: "state".
