### ISSUE TITLE
Change "get subset details" button language and make button a text link

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-data-browser#77]
"Get Subset Details" becomes "View Data Summary" and becomes a text link as opposed to a CTA button

**Comment by wpears** [comment]
I'm curious whether changing the button to a link would send the wrong message about whether the data summary is available on the same page or a different page. That is, I believe a button is the more semantic way to trigger an action in an app, while a link tends to redirect to external or separate resources.

Is the intent here to make the "View Data Summary" button less prominent compared to the download buttons? We could do that by, eg. shrinking the font sizes and padding somewhat or changing the spacing of elements on the page so it's clearer what button belongs where.

**Comment by MattPerrine** [comment]
I understand your point @wpears. Right now the user is initially presented with the 'Download Entire Dataset' CTA, if they add filters they now have 2 active CTA's on screen ('Download Entire Dataset' and 'View Data Summary'). Once they select 'View Data Summary' they are presented with a third CTA ('Download Filtered Data'). So they now have 3 CTA's on screen, all with equal prominence. 

Let's see if this comes up as a point of confusion during the next round of user testing and we can discuss next steps at that point.
